### ISSUE TITLE
Make compatible with monolog v3 ?

### ISSUE THREAD

**Issue by manne65-hd** [filips123/MonologPHPMailer#2]
Hey there and thanks for this nice PHPMailer-Handler for monolog.
Is this REPO still "alive" ?

Is there any chance to make this work wiht the latest release of monolog (Version 3) ?

**Here's my current quick&dirty solution, which works with monolog 3.4**
* I use **/src/PHPMailerHandler2.php** which I renamed to **PHPMailerHandler.php**
* I renamed the class inside PHPMailerHandler2.php to PHPMailerHandler
* I removed ``` namespace MonologPHPMailer; ``` in the top section of that file

So maybe all that's required is to edit composer.json to also "allow" v3.x" of monolog, in order to make it compatible ?? 
But I am not sure about that!

Looking forward to your answer,
Manfred

**Comment by filips123** [comment]
I can try to update it to Monolog v3. Considering that Monolog v1 and v2 are also already quite old, I'll probably also remove support for them and release this in a new major version, as that will simplify the code.

**Comment by filips123** [comment]
I released 2.0.0 with support for Monolog v3. I hope it will work fine.

**Comment by manne65-hd** [comment]
Thank you very much ... works fine here ;-)
